### ISSUE TITLE
Thank you for publishing the source code to this

### ISSUE THREAD

**Issue by dtaht** [technicolor-research/cuckoopp#1]
It is rare that I read such a good paper, and then find source code to go with it that I can just fiddle with.

Thank you.

In my case, I've been trying to find a way to speed up the babeld daemon's "resend" oriented routines,
which use SADR routes (36 bytes), and also have a timeout associated with them. Presently (sigh) - it's a linked list which falls apart at a mere 10k routes. I considered rbtrees... but still had that pesky timeout...

I was merely trying to get to 64k routes, but hey, a few million wouldn't be bad.... :)

**Comment by nlescoua** [comment]
Thanks for the nice feedback.
